/****************************************************************************************************
	Object Type: 	Function
	Name       :    XXTWC_CLAIMS_GET_ROLE_ACCESS_LEVEL
	Created by:		Trinamix
	Created On:		06/01/2023
	Description:	Function for Role level access
	Modified On:	
	Reason:		    
****************************************************************************************************/
create or replace FUNCTION XXTWC_CLAIMS_GET_ROLE_ACCESS_LEVEL(P_ROLE_ID IN NUMBER , P_MODULE_NAME IN VARCHAR2 ,P_ACCESS_TYPE IN VARCHAR2
) 
RETURN NUMBER
IS
	LV_VIEW NUMBER;
	LV_INSERT NUMBER;
	LV_UPDATE NUMBER;
	LV_DELETE NUMBER;
	LV_MENU NUMBER;
BEGIN
IF P_ACCESS_TYPE IS NULL 
THEN
SELECT COUNT(ROLE_ID) INTO LV_MENU
	FROM XXTWC_CLAIMS_ROLE_MODULES A, XXTWC_CLAIMS_MODULES B
	WHERE(ROLE_VIEW = '1' OR ROLE_INSERT = '1' OR ROLE_UPDATE = '1'  OR ROLE_DELETE = '1' )
	AND B.MOD_ID = A.MOD_ID
	AND UPPER(B.MOD_NAME) = UPPER(P_MODULE_NAME) 
	AND ROLE_ID = P_ROLE_ID
    AND SYSDATE BETWEEN NVL(EFF_START_DATE,SYSDATE) AND NVL(EFF_END_DATE,SYSDATE)
    AND A.STATUS = 1
    AND B.STATUS =1;
    
 
 IF LV_MENU <> 0
	THEN RETURN 1;
	ELSE RETURN 0;
 END IF;
ELSE 
 IF P_ACCESS_TYPE = 'VIEW'
 THEN
	SELECT COUNT(ROLE_ID) INTO LV_VIEW
	FROM XXTWC_CLAIMS_ROLE_MODULES A, XXTWC_CLAIMS_MODULES B
	WHERE ROLE_VIEW = '1' 
	AND B.MOD_ID = A.MOD_ID
	AND UPPER(B.MOD_NAME) = UPPER(P_MODULE_NAME) 
	AND ROLE_ID = P_ROLE_ID
    AND SYSDATE BETWEEN NVL(EFF_START_DATE,SYSDATE) AND NVL(EFF_END_DATE,SYSDATE)
    AND A.STATUS = 1
    AND B.STATUS =1;
    
 
 IF LV_VIEW <> 0
	THEN RETURN 1;
	ELSE RETURN 0;
 END IF;
 END IF;
 
 IF P_ACCESS_TYPE = 'INSERT'
 THEN
	SELECT COUNT(ROLE_ID) INTO LV_INSERT
	FROM XXTWC_CLAIMS_ROLE_MODULES A, XXTWC_CLAIMS_MODULES B
	WHERE ROLE_INSERT = '1'
	AND B.MOD_ID = A.MOD_ID
	AND UPPER(B.MOD_NAME) = UPPER(P_MODULE_NAME) 
	AND ROLE_ID = P_ROLE_ID 
     AND SYSDATE BETWEEN NVL(EFF_START_DATE,SYSDATE) AND NVL(EFF_END_DATE,SYSDATE)
    AND A.STATUS = 1
    AND B.STATUS =1;
 
 IF LV_INSERT <> 0
	THEN RETURN 2;
	ELSE RETURN 0;
 END IF;
 END IF;
 
 IF P_ACCESS_TYPE = 'UPDATE'
 THEN
	SELECT COUNT(ROLE_ID) INTO LV_UPDATE
	FROM XXTWC_CLAIMS_ROLE_MODULES A, XXTWC_CLAIMS_MODULES B
	WHERE ROLE_UPDATE = '1' 
	AND B.MOD_ID = A.MOD_ID
	AND UPPER(B.MOD_NAME) = UPPER(P_MODULE_NAME) 
	AND ROLE_ID = P_ROLE_ID 
     AND SYSDATE BETWEEN NVL(EFF_START_DATE,SYSDATE) AND NVL(EFF_END_DATE,SYSDATE)
    AND A.STATUS = 1
    AND B.STATUS =1;
 
 IF LV_UPDATE <> 0
	THEN RETURN 3;
	ELSE RETURN 0;
 END IF;
 END IF;
 
  IF P_ACCESS_TYPE = 'DELETE'
 THEN
	SELECT COUNT(ROLE_ID) INTO LV_DELETE
	FROM XXTWC_CLAIMS_ROLE_MODULES A, XXTWC_CLAIMS_MODULES B
	WHERE ROLE_DELETE = '1' 
	AND B.MOD_ID = A.MOD_ID
	AND UPPER(B.MOD_NAME) = UPPER(P_MODULE_NAME) 
	AND ROLE_ID = P_ROLE_ID 
     AND SYSDATE BETWEEN NVL(EFF_START_DATE,SYSDATE) AND NVL(EFF_END_DATE,SYSDATE)
    AND A.STATUS = 1
    AND B.STATUS =1;
 
 IF LV_DELETE <> 0
	THEN RETURN 4;
	ELSE RETURN 0;
 END IF;
 END IF;
  END IF;
END;
/
GRANT ALL ON CLAIMS.XXTWC_CLAIMS_GET_ROLE_ACCESS_LEVEL TO XXAPPS;