--------------------------------------------------------
--  File created - Wednesday-June-21-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table XXTWC_CLAIMS_APPR_LVL_DTL
--------------------------------------------------------

  CREATE TABLE "CLAIMS"."XXTWC_CLAIMS_APPR_LVL_DTL" 
   (	"APPR_LVL_DTL_ID" NUMBER, 
	"GROUP_ID" VARCHAR2(255 BYTE), 
	"MAX_VALUE" NUMBER, 
	"MIN_VALUE" NUMBER, 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"CREATED_BY" VARCHAR2(150 BYTE), 
	"CREATION_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(150 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"STATUS" NUMBER, 
	"APPR_LVL_HDR_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLAIMS_DATA" ;