--------------------------------------------------------
--  File created - Wednesday-June-21-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table XXTWC_CLAIMS_USER_LOGIN_DETAILS
--------------------------------------------------------

  CREATE TABLE "CLAIMS"."XXTWC_CLAIMS_USER_LOGIN_DETAILS" 
   (	"USER_ID" NUMBER, 
	"FIRSTNAME" VARCHAR2(50 BYTE), 
	"LASTNAME" VARCHAR2(50 BYTE), 
	"EMAIL_ID" VARCHAR2(50 BYTE), 
	"ACCESS_TO_APPS" VARCHAR2(4000 BYTE), 
	"PASSWORD" VARCHAR2(50 BYTE), 
	"ACTIVE_FLG" VARCHAR2(1 BYTE), 
	"IS_PASSWORD_CHANGE" VARCHAR2(1 BYTE), 
	"CREATION_DATE" DATE, 
	"CREATED_BY" VARCHAR2(100 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATE_BY" VARCHAR2(100 BYTE), 
	"SALT" VARCHAR2(20 BYTE), 
	"SSO_USER" VARCHAR2(1 BYTE), 
	"USER_IMG" BLOB, 
	"MIME_TYPE" VARCHAR2(1000 BYTE), 
	"IMG_FILE_NAME" VARCHAR2(1000 BYTE), 
	"DEPT_CODE" VARCHAR2(1000 BYTE),
	"USER_TIMEZONE" VARCHAR2(1000 BYTE),
	"VIEW_ALL_CLAIM" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLAIMS_DATA" 
 LOB ("USER_IMG") STORE AS SECUREFILE (
  TABLESPACE "CLAIMS_DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;