--------------------------------------------------------
--  File created - Wednesday-June-21-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table XXTWC_UNREF_CLAIMS_LINES
--------------------------------------------------------

  CREATE TABLE "CLAIMS"."XXTWC_UNREF_CLAIMS_LINES" 
   (	"CLAIM_DTL_ID" NUMBER, 
	"CLAIM_ID" NUMBER, 
	"CLAIM_LINE_NO" NUMBER, 
	"INVENTORY_ITEM_ID" NUMBER, 
	"INVENTORY_ITEM_NAME" VARCHAR2(100 BYTE), 
	"INVENTORY_ITEM_DESC" VARCHAR2(240 BYTE), 
	"LPN" VARCHAR2(50 BYTE), 
	"LOT_NUMBER" VARCHAR2(50 BYTE), 
	"UOM" VARCHAR2(100 BYTE), 
	"SHIP_QTY" NUMBER, 
	"CLAIM_QTY" NUMBER, 
	"UNIT_LIST_PRICE" NUMBER, 
	"UNIT_SELLING_PRICE" NUMBER, 
	"UNIT_ADJUSTMENT_PRICE" NUMBER, 
	"EXTENDED_AMOUNT" NUMBER, 
	"FRIGHT_CHARGES" NUMBER, 
	"ITEM_VARIETY" VARCHAR2(150 BYTE), 
	"ITEM_REGION" VARCHAR2(150 BYTE), 
	"ITEM_COUNTRY_OF_ORIG" VARCHAR2(150 BYTE), 
	"CLAIM_REASON_CODE" VARCHAR2(100 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 BYTE), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(255 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE_NUM1" NUMBER, 
	"ATTRIBUTE_NUM2" NUMBER, 
	"ATTRIBUTE_NUM3" NUMBER, 
	"ATTRIBUTE_NUM4" NUMBER, 
	"ATTRIBUTE_NUM5" NUMBER, 
	"ATTRIBUTE_DATE1" DATE, 
	"ATTRIBUTE_DATE2" DATE, 
	"ATTRIBUTE_DATE3" DATE, 
	"ATTRIBUTE_DATE4" DATE, 
	"ATTRIBUTE_DATE5" DATE, 
	"GL_ACCOUNT" VARCHAR2(150 BYTE), 
	"FULFILLMENT_LINE_ID" NUMBER, 
	"ERROR_MESSAGE" VARCHAR2(4000 BYTE), 
	"VAL_STATUS" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLAIMS_DATA" ;

