--------------------------------------------------------
--  File created - Wednesday-June-21-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table XXTWC_CLAIMS_DATA_ACT_LOG
--------------------------------------------------------

  CREATE TABLE "CLAIMS"."XXTWC_CLAIMS_DATA_ACT_LOG" 
   (	"TAB_AUDIT_ID" NUMBER, 
	"USER_ID" NUMBER, 
	"SESSION_ID" NUMBER, 
	"ACTION" VARCHAR2(20 BYTE), 
	"REASON" VARCHAR2(4000 BYTE), 
	"ATIME" TIMESTAMP (6), 
	"TAB_NAME" VARCHAR2(100 BYTE), 
	"REC_ID" NUMBER, 
	"AUDIT_TYPE" VARCHAR2(20 BYTE), 
	"COL_NAME" VARCHAR2(20 BYTE), 
	"OLD_VALUE" VARCHAR2(4000 BYTE), 
	"NEW_VALUE" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLAIMS_DATA" ;
