--------------------------------------------------------
--  File created - Wednesday-June-21-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table XXTWC_CLAIMS_APPR_WF_HEADER
--------------------------------------------------------

  CREATE TABLE "CLAIMS"."XXTWC_CLAIMS_APPR_WF_HEADER" 
   (	"WF_ID" NUMBER, 
	"WF_NAME" VARCHAR2(100 BYTE), 
	"CLAIM_TYPE" VARCHAR2(100 BYTE), 
	"ORG_ID" NUMBER, 
	"BU_NAME" VARCHAR2(240 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE_NUM1" NUMBER, 
	"ATTRIBUTE_NUM2" NUMBER, 
	"ATTRIBUTE_NUM3" NUMBER, 
	"ATTRIBUTE_NUM4" NUMBER, 
	"ATTRIBUTE_NUM5" NUMBER, 
	"ATTRIBUTE_DATE1" DATE, 
	"ATTRIBUTE_DATE2" DATE, 
	"ATTRIBUTE_DATE3" DATE, 
	"STATUS" VARCHAR2(1 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 BYTE), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(255 BYTE), 
	"DIRECT_FLAG" NUMBER, 
	"APPR_LVL_HDR_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLAIMS_DATA" ;
