--------------------------------------------------------
--  File created - Wednesday-June-21-2023   
--  06-Jul-2023 : added claim_note
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table XXTWC_CLAIMS_RMA_HEADERS_OUT
--------------------------------------------------------

  CREATE TABLE "CLAIMS"."XXTWC_CLAIMS_RMA_HEADERS_OUT" 
   (	"CLAIM_ID" NUMBER, 
	"CLAIM_NUMBER" VARCHAR2(100 BYTE), 
	"CLAIM_REVISION_NUMBER" NUMBER, 
	"CLAIM_DATE" DATE, 
	"ORG_ID" NUMBER, 
	"BU_NAME" VARCHAR2(240 BYTE), 
	"CLAIM_TYPE" VARCHAR2(100 BYTE), 
	"ORDER_NUMBER" VARCHAR2(100 BYTE), 
	"SOLD_TO_CUSTOMER_NAME" VARCHAR2(240 BYTE), 
	"SOLD_TO_PARTY_NUMBER" VARCHAR2(100 BYTE), 
	"SOURCE_TRANSACTION_NUMBER" VARCHAR2(100 BYTE), 
	"SOURCE_TRANSACTION_SYSTEM" VARCHAR2(100 BYTE), 
	"SOURCE_TRANSACTION_ID" VARCHAR2(100 BYTE), 
	"TRANSACTION_TYPE_CODE" VARCHAR2(100 BYTE), 
	"REQUESTED_FULFIL_ORG_CODE" VARCHAR2(100 BYTE), 
	"SHIP_TO_PARTY_ID" NUMBER, 
	"SHIP_TO_CUSTOMER_NAME" VARCHAR2(240 BYTE), 
	"SHIP_TO_SITE_ID" NUMBER, 
	"BILL_TO_CUSTOMER_ID" NUMBER, 
	"BILL_TO_CUSTOMER_NAME" VARCHAR2(240 BYTE), 
	"BILL_TO_SITE_USE_ID" NUMBER, 
	"CLAIM_REC_DATE" DATE, 
	"CLAIM_CURRENCY_CODE" VARCHAR2(10 BYTE), 
	"CLAIM_STATUS" VARCHAR2(20 BYTE), 
	"CREATION_DATE" DATE, 
	"CREATED_BY" VARCHAR2(255 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(255 BYTE), 
	"LAST_UPDATED_LOGON" VARCHAR2(255 BYTE), 
	"ORA_RMA_HEADER_ID" NUMBER, 
	"ORA_RMA_NO" VARCHAR2(150 BYTE), 
	"ORA_RMA_STATUS" VARCHAR2(150 BYTE), 
	"ORA_RMA_INT_STATUS" VARCHAR2(10 BYTE), 
	"ORA_RMA_INT_MSG" VARCHAR2(4000 BYTE), 
	"HEADER_ID" NUMBER, 
	"CSR_NAME" VARCHAR2(300 BYTE), 
	"PREVENTABLE" VARCHAR2(30 BYTE), 
	"PROCESS_TYPE" VARCHAR2(30 BYTE), 
	"OIC_INSTANCE_ID" VARCHAR2(50 BYTE), 
	"REBILL_TO_OTHER_CUST" VARCHAR2(1 BYTE), 
	"PRICE_ADJ_ONLY" VARCHAR2(1 BYTE), 
	"INSPECTION" VARCHAR2(1 BYTE), 
	"SALES_PERSON_ID" NUMBER,
	"CLAIM_NOTE" VARCHAR2(240 BYTE) ,	
	"PO_NUMBER" VARCHAR2(100 BYTE),
	"EXPORT_ORDER"  VARCHAR2(1),
	"CONSIGNMENT_ORDER"  VARCHAR2(1)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLAIMS_DATA" ;
