--------------------------------------------------------
--  File created - Wednesday-June-21-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table XXTWC_CLAIMS_USER_MANUAL
--------------------------------------------------------

  CREATE TABLE "CLAIMS"."XXTWC_CLAIMS_USER_MANUAL" 
   (	"USER_MANUAL_ID" NUMBER, 
	"URL_LINK" VARCHAR2(1000 BYTE), 
	"USER_MANUAL" BLOB, 
	"MIME_TYPE" VARCHAR2(1000 BYTE), 
	"FILE_NAME" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"CREATED_BY" VARCHAR2(150 BYTE), 
	"CREATION_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(150 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"STATUS" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "CLAIMS_DATA" 
 LOB ("USER_MANUAL") STORE AS SECUREFILE (
  TABLESPACE "CLAIMS_DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;