--------------------------------------------------------
--  File created - Wednesday-June-21-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table XXTWC_CLAIMS_DOCUMENTS
--------------------------------------------------------

  CREATE TABLE "CLAIMS"."XXTWC_CLAIMS_DOCUMENTS" 
   (	"CLAIM_DOC_ID" NUMBER, 
	"CLAIM_ID" NUMBER, 
	"CLAIM_DTL_ID" NUMBER, 
	"FILE_ID" VARCHAR2(150 BYTE), 
	"DOCUMENT_CATEGORY" VARCHAR2(150 BYTE), 
	"FILE_NAME" VARCHAR2(240 BYTE), 
	"FILE_EXT" VARCHAR2(240 BYTE), 
	"FILE_COMMENT" VARCHAR2(240 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 BYTE), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLAIMS_DATA" ;
