--------------------------------------------------------
--  File created - Wednesday-June-21-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table XXTWC_CLAIMS_LOOKUPS
--------------------------------------------------------

  CREATE TABLE "CLAIMS"."XXTWC_CLAIMS_LOOKUPS" 
   (	"LOOKUP_ID" NUMBER, 
	"LOOKUP_NAME" VARCHAR2(250 BYTE), 
	"LOOKUP_VALUE" VARCHAR2(250 BYTE), 
	"LOOKUP_TYPE" VARCHAR2(250 BYTE), 
	"ATTRIBUTE1" VARCHAR2(250 BYTE), 
	"ATTRIBUTE2" VARCHAR2(250 BYTE), 
	"ATTRIBUTE3" VARCHAR2(250 BYTE), 
	"ATTRIBUTE4" VARCHAR2(250 BYTE), 
	"ATTRIBUTE5" VARCHAR2(250 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 BYTE), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(255 BYTE), 
	"STATUS" VARCHAR2(1 BYTE), 
	"USER_IMG" BLOB, 
	"MIME_TYPE" VARCHAR2(1000 BYTE), 
	"IMG_FILE_NAME" VARCHAR2(1000 BYTE),
	"ATTRIBUTE6" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLAIMS_DATA" 
 LOB ("USER_IMG") STORE AS SECUREFILE (
  TABLESPACE "CLAIMS_DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;