--------------------------------------------------------
--  File created - Wednesday-June-21-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table XXTWC_CLAIMS_SO_LINES_OUT
--------------------------------------------------------

  CREATE TABLE "CLAIMS"."XXTWC_CLAIMS_SO_LINES_OUT" 
   (	"CLAIM_DTL_ID" NUMBER, 
	"CLAIM_ID" NUMBER, 
	"CLAIM_LINE_NO" NUMBER, 
	"FULFILLMENT_LINE_ID" NUMBER, 
	"SOURCE_TRANSACTION_LINEID" NUMBER, 
	"SOURCE_TRANSACTION_LINE_NUMBER" NUMBER, 
	"SOURCE_SCHEDULE_NUMBER" NUMBER, 
	"SOURCE_TRANSACTION_SCHEDULE_ID" NUMBER, 
	"ORDERED_UOM_CODE" VARCHAR2(100 BYTE), 
	"CLAIM_QTY" NUMBER, 
	"INVENTORY_ITEM_NUMBER" VARCHAR2(100 BYTE), 
	"INVENTORY_ITEM_ID" NUMBER, 
	"TRANSACTION_CATEGORY_CODE" VARCHAR2(100 BYTE), 
	"TRANSACTION_LINE_TYPE_CODE" VARCHAR2(100 BYTE), 
	"UNIT_LIST_PRICE" NUMBER, 
	"UNIT_SELLING_PRICE" NUMBER, 
	"UNIT_ADJUSTMENT_PRICE" NUMBER, 
	"ADJUSTMENT_AMOUNT" NUMBER, 
	"ADJUSTMENT_TYPE_CODE" VARCHAR2(100 BYTE), 
	"CHARGE_DEFINITION_CODE" VARCHAR2(100 BYTE), 
	"CHARGE_ROLLUP_FLAG" VARCHAR2(100 BYTE), 
	"CHARGE_REASON_CODE" VARCHAR2(100 BYTE), 
	"SOURCE_MANUAL_PRICE_ADJ_ID" NUMBER, 
	"FRIGHT_CHARGES" NUMBER, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" VARCHAR2(255 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(255 BYTE), 
	"ORA_SO_LINE_ID" NUMBER, 
	"ORA_SO_LINE_STATUS" VARCHAR2(255 BYTE), 
	"LPN" VARCHAR2(50 BYTE), 
	"LOT_NUMBER" VARCHAR2(50 BYTE), 
	"CURRENCY_CODE" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLAIMS_DATA" ;
