create or replace FUNCTION XXTWC_CAR_AUTHROLE_ACCESS(P_USER_NAME IN VARCHAR2) 
RETURN NUMBER
IS
L_ROLE_NAME VARCHAR2(100);
BEGIN
	SELECT ROLE_NAME 
	INTO L_ROLE_NAME
	FROM XXTWC_CAR_ROLES R,XXTWC_CAR_ROLES_USER RU
	WHERE R.ROLE_ID = RU.ROLE_ID
	AND UPPER(USER_NAME) = UPPER(P_USER_NAME)
	AND RU.STATUS = 1;

	IF L_ROLE_NAME = 'TWC_CAR_ADMIN' THEN
		RETURN 0;
	ELSIF L_ROLE_NAME = 'TWC_CAR_APPROVER' THEN
		RETURN 1;
	ELSIF L_ROLE_NAME = 'TWC_CAR_REQUESTER' THEN
		RETURN 2;
	END IF;
	EXCEPTION WHEN OTHERS THEN
		RETURN 2;

END;
/