--------------------------------------------------------
--  DDL for Trigger XXTWC_AUDIT_TABS_CLAIMS_USERS_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "CLAIMS"."XXTWC_AUDIT_TABS_CLAIMS_USERS_TRG" 
  AFTER insert OR UPDATE on "XXTWC_CLAIMS_USERS"
  for each row
  DECLARE
  LV_AUDIT_ID NUMBER;
BEGIN
if inserting then
SELECT XXTWC_CLAIMS_DATA_ACT_LOG_SEQ.nextval INTO LV_AUDIT_ID FROM DUAL;
INSERT INTO XXTWC_CLAIMS_DATA_ACT_LOG (TAB_AUDIT_ID,USER_ID,SESSION_ID,ACTION,REASON,ATIME,TAB_NAME,REC_ID,AUDIT_TYPE,COL_NAME,OLD_VALUE,NEW_VALUE)
VALUES
(LV_AUDIT_ID,APEX_UTIL.GET_CURRENT_USER_ID,v('APP_SESSION'),'INSERT','INSERTED On'||' '||systimestamp,SYSTIMESTAMP,'XXTWC_CLAIMS_USERS',:NEW.USER_ID,NULL,NULL,NULL,NULL);

ELSIF UPDATING THEN
IF :NEW.USER_NAME <> :OLD.USER_NAME
THEN
SELECT XXTWC_CLAIMS_DATA_ACT_LOG_SEQ.nextval INTO LV_AUDIT_ID FROM DUAL;
INSERT into XXTWC_CLAIMS_DATA_ACT_LOG (TAB_AUDIT_ID,USER_ID,SESSION_ID,ACTION,REASON,ATIME,TAB_NAME,REC_ID,AUDIT_TYPE,COL_NAME,OLD_VALUE,NEW_VALUE)
VALUES(LV_AUDIT_ID,APEX_UTIL.GET_CURRENT_USER_ID, v('APP_SESSION') ,'UPDATE','UPDATED On'||' '||systimestamp,SYSTIMESTAMP,'XXTWC_CLAIMS_USERS',:NEW.USER_ID,
'VARCHAR2','USER_NAME',:OLD.USER_NAME,:NEW.USER_NAME);
END IF;

IF :NEW.PASSWORD <> :OLD.PASSWORD
THEN
SELECT XXTWC_CLAIMS_DATA_ACT_LOG_SEQ.nextval INTO LV_AUDIT_ID FROM DUAL;
INSERT into XXTWC_CLAIMS_DATA_ACT_LOG (TAB_AUDIT_ID,USER_ID,SESSION_ID,ACTION,REASON,ATIME,TAB_NAME,REC_ID,AUDIT_TYPE,COL_NAME,OLD_VALUE,NEW_VALUE)
VALUES(LV_AUDIT_ID,APEX_UTIL.GET_CURRENT_USER_ID,v('APP_SESSION'),'UPDATE','UPDATED On'||' '||systimestamp,SYSTIMESTAMP,'XXTWC_CLAIMS_USERS',:NEW.USER_ID,
'VARCHAR2','PASSWORD',:OLD.PASSWORD,:NEW.PASSWORD);
END IF;

IF nvl(:NEW.CREATION_DATE,sysdate) <> nvl(:OLD.CREATION_DATE,sysdate)
THEN
SELECT XXTWC_CLAIMS_DATA_ACT_LOG_SEQ.nextval INTO LV_AUDIT_ID FROM DUAL;
INSERT into XXTWC_CLAIMS_DATA_ACT_LOG (TAB_AUDIT_ID,USER_ID,SESSION_ID,ACTION,REASON,ATIME,TAB_NAME,REC_ID,AUDIT_TYPE,COL_NAME,OLD_VALUE,NEW_VALUE)
VALUES (LV_AUDIT_ID,APEX_UTIL.GET_CURRENT_USER_ID,v('APP_SESSION'),'UPDATE','UPDATED On'||' '||systimestamp,SYSTIMESTAMP,'XXTWC_CLAIMS_USERS',:NEW.USER_ID,
'TIMESTAMP','CREATION_DATE',:OLD.CREATION_DATE,:NEW.CREATION_DATE);
END IF;

end if;
end;
/
ALTER TRIGGER "CLAIMS"."XXTWC_AUDIT_TABS_CLAIMS_USERS_TRG" ENABLE;